version: '3'

services:
  web:
    buid: .
    image: golang:1.13.0-alpine3.10
    restart: always
    ports:
      - 8888:8000
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
    networks:
      concertnet
  redis:
    image: redis:5.0.5-alpine
    environment:
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/redis/data"
    networks:
      - concertnet

volumes:
  redis_data:
    driver:

networks:
  concertnet